### ISSUE TITLE
ReferenceError: IDBObjectStore is not defined

### ISSUE THREAD

**Issue by spolepaka** [darrachequesne/synceddb#5]
The code is giving the following build and also run time error with "npm run build" / "npm run dev" on importing openDB, SyncManager or LiveQuery:

 ⨯ ReferenceError: IDBObjectStore is not defined
    at file:///workspaces/test/node_modules/synceddb/build/wrap-idb-value.js:33:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15) {
  page: '/'
}

The code is simply importing with the code:
import { openDB, SyncManager, LiveQuery } from "synceddb";

Initially on Next JS version 13.4.6  but later upgraded to 13.5.4 still the same error.

**Comment by darrachequesne** [comment]
Hi! Which browser are you using?

`IDBObjectStore` should be available in most browsers: https://caniuse.com/mdn-api_idbobjectstore

**Comment by spolepaka** [comment]
It is not working on any browser. I tried Chrome, Brave, Edge. I don't think it is browser related, it is giving me an error while building (npm run build) as well.

**Comment by darrachequesne** [comment]
I think that I have found the culprit! You need to declare your component as a client component, by adding `'use client'` at the top of your file. This way, you will have access to the IndexedDB API.

```js
'use client'

import { openDB } from 'synceddb';

// ...
```

Reference: https://nextjs.org/docs/app/building-your-application/rendering/client-components

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
