### ISSUE TITLE
synceddb still used / maintained? Browser JS file available?

### ISSUE THREAD

**Issue by pwFoo** [darrachequesne/synceddb#6]
Hi @darrachequesne,

found your project and really like it. Is it still used and maintained?

I use JS in browser only. So is there a browser ready JS file available? Searched the demo, but there isn't a file / cdn link:
```
<script src="node_modules/synceddb/build/umd.js"></script>
```

**Comment by pwFoo** [comment]
Found a browser ready file:
https://www.npmjs.com/package/synceddb/v/0.0.2?activeTab=code -> build/umd.js

**Comment by darrachequesne** [comment]
> found your project and really like it. Is it still used and maintained?

Yes it is!

> So is there a browser ready JS file available?

You can indeed use the `build/umd.js` file.

You can also import the bundle from a CDN: 

```html
<script src="https://cdn.jsdelivr.net/npm/synceddb@0/build/umd.js"></script>
```

Or import it with a bundler:

```js
import { openDB, SyncManager } from 'synceddb';
```

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
